FROM nginx:latest
RUN mkdir /app
COPY ./app/app.js /app
EXPOSE 3000
COPY nginx.conf /etc/nginx/nginx.conf

FROM node:latest
WORKDIR /app
COPY app/package.json /app
RUN npm install
COPY ./app /app
EXPOSE 3000
CMD ["npm", "start"]
USER node