version: "3"
services:
    website2:
        container_name: website2
        # ports:
        # - 3000
        environment:
            - VIRTUAL_HOST=ijustwanna.win
            - LETSENCRYPT_HOST=ijustwanna.win
            - LETSENCRYPT_EMAIL=warburtonroland@gmail.com
            - VIRTUAL_PORT=3000
            - VIRTUAL_NETWORK=proxy-network
            # - VIRTUAL_PROTO=https
        image: website2
        # image: nginx
        # image: httpd:alpine

networks:
    default:
        external:
            name: nginx-proxy
#
# expose vs ports:
# EXPOSE: expose this port to other docker containers
# PORTS: this port is accessed by the outside world

# version: '3'

# services:
#   example-app:
#     image: example/example-app
#     expose:
#       - 80
#     environment:
#       VIRTUAL_HOST: app.example.com
#       LETSENCRYPT_HOST: app.example.com
#       LETSENCRYPT_EMAIL: foo@example.com

# networks:
#     default:
#         external:
#             name: nginx-proxy
