FROM nginx:latest
EXPOSE 3000
COPY ./docker/nginx.conf /etc/nginx/nginx.conf

FROM node:14

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY ./app/package.json /usr/src/app
RUN npm install

# Bundle app source
COPY ./app /usr/src/app

# Exports
EXPOSE 3000
CMD [ "npm", "run", "start" ]
