version: "3"
services:
    template01:
        container_name: template01
        image: express
        environment:
            - PORT=3000
            - LABEL=3001
        ports:
            - 127.0.0.1:3001:3000
    template02:
        container_name: template02
        image: express
        environment:
            - PORT=3000
            - LABEL=3002
        ports:
            - 127.0.0.1:3002:3000

networks:
    default:
        external:
            name: gateway_network
