version: "3"
services:
    template01:
        container_name: template01
        image: express
        environment:
            - PORT=3001
            - LABEL=3001
        ports:
            - 3001:3000
    template02:
        container_name: template02
        image: express
        environment:
            - PORT=3002
            - LABEL=3002
        ports:
            - 3002:3000
