FROM nginx:latest

USER root
# place in some custom html stuff here
# RUN mkdir -p /usr/share/nginx/html
COPY ./html /usr/share/nginx/html
# RUN chown nginx:nginx /usr/share/nginx/html/*
# RUN chown nginx:nginx /usr/share/nginx/html
# USER root
# COPY ./html/index.html /usr/share/nginx/html/index.html
# COPY ./html/favicon.ico /usr/share/nginx/html/favicon.ico

# place in the custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
EXPOSE 443