version: "3.0"
services:
    gateway:
        container_name: "gateway"
        image: gateway
        ports:
            - "80:80"
            - "443:443"
        # network_mode: "host"
        volumes:
            - "/etc/letsencrypt/live/0x8.host/fullchain.pem:/etc/letsencrypt/live/0x8.host/fullchain.pem"
            - "/etc/letsencrypt/live/0x8.host/privkey.pem:/etc/letsencrypt/live/0x8.host/privkey.pem"

networks:
    default:
        external:
            name: gateway_network
