version: "3"
services:
    website:
        container_name: website
        # expose:
        # - 80
        environment:
            - VIRTUAL_HOST=ijustwanna.win
            - LETSENCRYPT_HOST=ijustwanna.win
            - LETSENCRYPT_EMAIL=warburtonroland@gmail.com
            - VIRTUAL_PORT=3001
            - VIRTUAL_NETWORK=proxy-network
        image: website
        # image: nginx
        # image: httpd:alpine
#
# expose vs ports:
# EXPOSE: expose this port to other docker containers
# PORTS: this port is accessed by the outside world

# version: '3'

# services:
#   example-app:
#     image: example/example-app
#     expose:
#       - 80
#     environment:
#       VIRTUAL_HOST: app.example.com
#       LETSENCRYPT_HOST: app.example.com
#       LETSENCRYPT_EMAIL: foo@example.com

# networks:
#     default:
#         external:
#             name: nginx-proxy
