FROM nginx:latest
RUN mkdir /app
COPY ./app/app.js /app
EXPOSE 3001
COPY nginx.conf /etc/nginx/nginx.conf

FROM node:latest
WORKDIR /app
COPY app/package.json /app
RUN npm install
COPY ./app /app
EXPOSE 3001
CMD ["npm", "start"]
USER node

# FROM nginx:latest
# # RUN mkdir /app
# # COPY ./app/app.js /app
# COPY nginx.conf /etc/nginx/nginx.conf

# FROM node:latest
# WORKDIR /app
# COPY app/package.json /app
# RUN npm install
# COPY ./app /app
# CMD ["npm", "start"]

